# Generated by Django 5.1.1 on 2024-10-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('blood_type', models.TextField(max_length=40)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField(null=True)),
            ],
        ),
    ]
